In [1]:
import pandas as pd
import numpy as np

from datasets import load_dataset
from tqdm.notebook import tqdm

In [3]:
df = pd.read_parquet('./files_all/part_0/0a0ef7c39f2819f25320440743813a88.parquet')
df.head()

,uid,url,text,original_width,original_height,clip_l14_similarity_score,sha256,l14_img,l14_txt
0,043e318459cc7d2bf89e4125476a123a,https://maps.googleapis.com/maps/api/staticmap...,company map,400,300,0.200562,0aa97b6c335abb17e64bd9029965cad4259a2e2e738f81...,"[0.01239776611328125, 0.08319091796875, -0.002...","[-0.0035724639892578125, 0.0179290771484375, 0..."
1,ff2aead51ce8ac8c0a7e8bd2aca3fada,http://www.bnu1.org/uploads/editor/20191126/15...,6.3.jpg,1080,661,0.142090,fb9c93e6cad04318776f4b0931472446774c5d9d0c0a92...,"[0.060546875, 0.053680419921875, 0.06292724609...","[0.031524658203125, 0.021514892578125, -0.0233..."
2,6ce26a76ade73b438a688cf0b4be98e3,https://static1.squarespace.com/static/567d7b8...,TITANBELOArtboard 3.png,1000,971,0.096375,e2f6c7886c68c14521c8fed8c3d635b7c5a38745a3b828...,"[0.043365478515625, 0.00986480712890625, 0.011...","[-0.03363037109375, 0.0777587890625, -0.009346..."
3,712ae27068de10fba68f8b1fa71191be,https://static-maps.yandex.ru/1.x/?l=map&lang=...,Мебель 2х2 на карте Костромы,518,137,0.139404,5a5df3203ac21b1b8e781c58fa33e5aa74b7ad2f708270...,"[0.03167724609375, 0.060333251953125, 0.022277...","[-0.040679931640625, 0.0304718017578125, -0.00..."
4,7d65638803240ad896836a92c3d114f8,https://maps.googleapis.com/maps/api/staticmap...,Static map,600,400,0.173462,0215532ec8e0292c9159096609218c5967b85469be07c2...,"[-0.0195465087890625, 0.024505615234375, -0.00...","[-0.00739288330078125, 0.023895263671875, 0.03..."

In [8]:
df[df['uid'] == 'ed2b2a64df2c0ea4793e7e8fce762057']

,uid,url,text,original_width,original_height,clip_l14_similarity_score,sha256,l14_img,l14_txt
1330,ed2b2a64df2c0ea4793e7e8fce762057,https://plot.ly/~cimar/211.png,"Life Expectancy v. Per Capita GDP, 2007",560,498,0.256348,63746ef1fae35483bc0c9838aac1f475135519d40813b0...,"[0.021759033203125, -0.00787353515625, -0.0192...","[-0.0328369140625, 0.00731658935546875, -0.000..."

In [7]:
df_processed = pd.read_parquet('./processed/part_0/0a0ef7c39f2819f25320440743813a88_processed.parquet')
df_processed

,uid,url,score,pos_keys,neg_keys,l14_img
0,043e318459cc7d2bf89e4125476a123a,https://maps.googleapis.com/maps/api/staticmap...,0.0,,,"[0.012397766, 0.08319092, -0.0026226044, -0.09..."
1,ff2aead51ce8ac8c0a7e8bd2aca3fada,http://www.bnu1.org/uploads/editor/20191126/15...,0.0,,,"[0.060546875, 0.05368042, 0.062927246, 0.02853..."
2,6ce26a76ade73b438a688cf0b4be98e3,https://static1.squarespace.com/static/567d7b8...,0.0,,,"[0.04336548, 0.009864807, 0.011871338, -0.0051..."
3,712ae27068de10fba68f8b1fa71191be,https://static-maps.yandex.ru/1.x/?l=map&lang=...,0.0,,,"[0.031677246, 0.060333252, 0.022277832, -0.019..."
4,7d65638803240ad896836a92c3d114f8,https://maps.googleapis.com/maps/api/staticmap...,0.0,,,"[-0.019546509, 0.024505615, -0.0025119781, -0...."
...,...,...,...,...,...,...
3100,7811f3b2951ffb468cdba5e5c7dc598c,https://www.frostitpink.com/img/saffron-extrac...,0.0,,,"[0.0074539185, 0.05657959, -0.01309967, -0.025..."
3101,6968a48bb707410a0476913731d57e63,https://c8.alamy.com/comp/PA5TH0/218-ritningar...,0.0,,,"[0.039489746, 0.041259766, -0.018371582, 0.077..."
3102,15322227712648718f9f5ddb738e82c3,https://www.jackets-to-go.de/media/image/produ...,-3.0,,flag,"[-0.03050232, 0.06524658, 0.014831543, -0.0016..."
3103,ed2372b16edc66648a6adc3236f5677d,https://kadara.ru/wp-content/cache/thumb/ff/eb...,2.0,covid|covid-19,,"[0.00705719, 0.020950317, -0.0040512085, 0.015..."
3104,fbf7cbc52573fdc623a2e202111cf515,https://s3.amazonaws.com/gp-maps/event4008.png...,0.0,,,"[0.05557251, 0.042175293, 0.011253357, -0.0287..."

In [7]:
df_finished = pd.read_parquet('./data_preselection/checkpoint_137_rows_68500000.parquet')
df_finished.head()

df_finished.head(15)

,idx,url,score,pos_keys,neg_keys
0,68000000,https://france3-regions.francetvinfo.fr/image/...,-2.5,,km|sentiers
1,68000001,https://hebstreits.com/wp-content/uploads/2018...,0.0,,
2,68000002,https://www.dhresource.com/0x0s/f2-albu-g1-M00...,-2.5,size,image
3,68000003,https://image2.homes.jp/smallimg/image.php?fil...,0.0,,
4,68000004,http://tse4.mm.bing.net/th?id=OIP.Wb23awxWkmo-...,0.0,,
5,68000005,https://i2.wp.com/difficultrun.nathanielgivens...,0.0,,
6,68000006,https://maps.googleapis.com/maps/api/staticmap...,0.0,,
7,68000007,http://toursmaps.com/wp-content/uploads/2016/0...,-5.0,,tourist|attractions
8,68000008,https://housing.dasa.ncsu.edu/wp-content/uploa...,-2.0,,apartments
9,68000009,http://t.mapas.owje.com/2303_Hoja-Burlington-d...,0.0,,
10,68000010,https://ctl.s6img.com/society6/img/DHQsAKANSVi...,-2.0,,print
11,68000011,https://explora24.com/wp-content/uploads/2020/...,0.0,,
12,68000012,http://media3.paperblog.fr/i/543/5433268/poiss...,0.0,,
13,68000013,https://img.yumpu.com/37215060/1/184x260/deep-...,-2.0,,hotel
14,68000014,https://maps.allosurf.net/swell/wam_1/morbihan...,0.0,,

In [9]:
df_to_check = pd.read_parquet('000229558fb8787ec73b7658d3874f4a.parquet')

# ile urli występuje w obu
unique_urls = df_to_check['url'].unique()
unique_urls_finished = df_finished['url'].unique()
print(f"Unique URLs to check: {len(unique_urls)}")
print(f"Unique URLs finished: {len(unique_urls_finished)}")

# ile urli jest wspólnych w obu
common_urls = np.intersect1d(unique_urls, unique_urls_finished)
print(f"Common URLs: {common_urls}")

Unique URLs to check: 3232
Unique URLs finished: 479996
Common URLs: ['http://a.mktgcdn.com/p/7HqMOGY8tBw_oIJn6FwDM7vsDRoC8AWSB8PGw4ZOdyk/480x240.jpg'
 'http://academicexchange.com/wp-content/uploads/2015/07/1500x675-21.jpg'
 'http://assets.weather-forecast.com/maps/static/t_BritishVirginIslands.lapse.66.cc23.jpg'
 'http://assets.weather-forecast.com/maps/static/t_France.wind.36.cc23.jpg'
 'http://assets.weather-forecast.com/maps/static/t_India.wind.18.cc23.jpg'
 'http://assets.weather-forecast.com/maps/static/t_Madagascar.wind.186.cc23.jpg'
 'http://backgroundchecks.org/wp-content/uploads/2017/10/136059_OnlineDatingHeatMap-01_101617.png'
 'http://cdn.niusouti.com/cms/doc/47.jpg'
 'http://digitalizowanie.pl/wp-content/uploads/2017/01/skanowanie-slajdow-program-2.jpg'
 'http://img.testshappy.com/rtq9yscuxhfwmd705v8g1354.jpg'
 'http://img.yonhapnews.co.kr/etc/press/PR/2005/0000513051202135401_0.jpg'
 'http://info-4all.ru/wp-content/uploads/2017/09/cropped-test.png'
 'http://n.sinaimg.cn/news/1_img/upload/8de453bf/102/w1024h678/20180415/MR6l-fytnfyp5032500.jpg'
 'http://ontheworldmap.com/usa/national-park/death-valley/death-valley-location-on-the-us-map.jpg'
 'http://s1.eventfinder.co.nz/images/global/iconVenue-6.png'
 'http://s2.feedou.com/xgt/icolor/6/6506b3f774a10f19.jpg!w300xh300'
 'http://s3.onthesnow.com/images/trailmaps/slovakia/poracska-dolina/20140108055047/mid.jpg'
 'http://static-maps.yandex.ru/1.x/?l=map&ll=58.88620200,55.73633600&size=600,250&z=15'
 'http://static-s1.sanego.de/r20130524111119/img/map_marker/I.png'
 'http://t.mapas.owje.com/6373_Mapa-de-Industria-y-Mineria-de-Sudafrica.jpg'
 'http://t0.gstatic.com/images?q=tbn:ANd9GcQOOjinogs_WquOYiRxJyEKfXg3v_4XpJyfdaF5IgD2d_8rFT96i9mAAtmn'
 'http://t0.gstatic.com/images?q=tbn:ANd9GcQkC2XWsDPbdyu0GKZW6ygezpoKrkpACZcRm8KxBpzsG2YMXB33Pg'
 'http://t0.gstatic.com/images?q=tbn:ANd9GcQnWhRsGJOqndQWFflmGZGzd4XDe55IDrLkJPc3Za1cK-7ZHuw8DA'
 'http://t0.gstatic.com/images?q=tbn:ANd9GcQqQeNqMBM-klgSMX7njbZxmvT16TbY7AVl_ONkJlp-mOnNaI8Exg'
 'http://t0.gstatic.com/images?q=tbn:ANd9GcS8SNXBRKKcnsqdvgRdsrcIn7OIQ9IKecW9yyNw_-HZsCPsNJrx'
 'http://tse1.mm.bing.net/th?id=OIP.GZa3Nfu_DeIYx4BkQNcqGAHaHY'
 'http://tse1.mm.bing.net/th?id=OIP.URZBpXjqbRkReS7FErjgLQEsDw'
 'http://tse1.mm.bing.net/th?id=OIP.XOQnbng5-M5NayX4zP5_5wHaFj'
 'http://tse2.mm.bing.net/th?id=OIP.8rg5ecaGw7TaX0P8yrjs7gHaF7'
 'http://tse2.mm.bing.net/th?id=OIP.PBPO0wkJyalfx3F3kXCRqgHaK6'
 'http://tse2.mm.bing.net/th?id=OIP.XgWwzlxtg3AjldSdd7ThoQHaFj'
 'http://tse2.mm.bing.net/th?id=OIP.qugSmQ8-ew5bww1tahCGKAHaKo'
 'http://tse2.mm.bing.net/th?id=OIP.wRYfd8zMrRU5UkYA5KZHXwEsDU'
 'http://tse3.mm.bing.net/th?id=OIP.3fwTXZmUr7ihY_33KfLkjgHaFV'
 'http://tse3.mm.bing.net/th?id=OIP.mfjGEelSEFk2jXH4Hh_9vQEsEs'
 'http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Map_of_USA_with_state_names_2.svg/712px-Map_of_USA_with_state_names_2.svg.png'
 'http://ville-data.com/image/carte-france.jpg'
 'http://www.2carpros.com/forum/automotive_pictures/307270_1995_Chevy_Truck_Convenience_center_1.jpg'
 'http://www.56whcsj.com/wp-content/themes/wuliu/images/slt/img0147.jpg'
 'http://www.WeGoPlaces.com/user%20interface/images/REDMarkerA.png'
 'http://www.WeGoPlaces.com/user%20interface/images/REDMarkerP.png'
 'http://www.appenninoproperties.com/wp-content/uploads/property/casa-saldoni/PROGETTO_3-PIANTA-PIANO-PRIMO.jpg'
 'http://www.askmap.net/images/poi.png'
 'http://www.autogenius.info/wp-content/uploads/2016/05/Chevrolet-Silverado-fuse-box-underhood-electrical-center.jpg'
 'http://www.autogenius.info/wp-content/uploads/2016/10/Cadillac-SRX-mk2-fuse-box-engine-compartment.jpg'
 'http://www.autogenius.info/wp-content/uploads/2017/01/gmc-yukon-fuse-box-engine-compartment.jpg'
 'http://www.avtaf.com/wp-content/uploads/2018/09/Horoscope-Oracle--110x75.jpg'
 'http://www.earthquakenewstoday.com/wp-content/uploads/20_x65.jpg'
 'http://www.earthquakenewstoday.com/wp-content/uploads/45_x110.jpg'
 'http://www.mairie.com/img/ile_de_france.png'
 'http://www.maliburacing.com/wiring_diagrams/IgnitionSwitch.jpg'
 'http://www.neaq.org/wp-content/uploads/2016/07/map.jpg'
 'http://www.rydertowing.co.uk/images/car-data/II.png'
 'http://www.softoware.org/data/images/logo_web.jpg'
 'http://www.spord.cn/skin/web/network.jpg'
 'http://yellowpage.fixy.com.tw/pub/img/maps/location/map_tag2.png'
 'https://allpunjab.in/images/Web_Images/webicon.png'
 'https://assets.weather-forecast.com/maps/static/Zimbabwe.prec.6.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Afghanistan.lapse.150.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Afghanistan.prec.54.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Antarctica.prec.240.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Argentina.lapse.180.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Argentina.lapse.222.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Austria.wind.24.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Austria.wind.48.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_BritishVirginIslands.lapse.216.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_CanaryIslandsSpain.cloud.30.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Cuba.lapse.120.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Cuba.prec.102.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Florida.prec.90.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_France.wind.234.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Ghana.lapse.150.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Ghana.lapse.72.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Ghana.prec.96.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Global-Pacific.prec.60.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Guinea.lapse.114.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Guinea.lapse.180.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Guinea.prec.162.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Guinea.wind.66.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Honduras.lapse.204.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Honduras.prec.180.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Honduras.prec.198.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Iceland.wind.36.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Indian-Ocean.cloud.150.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Madagascar.lapse.150.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Maine.prec.210.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Missouri.wind.198.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_New-South-Wales.lapse.198.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_North-Carolina.lapse.108.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Pacific-Ocean.prec.30.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Saskatchewan.wind.180.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Sweden.wind.126.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Thailand.lapse.126.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Uganda.lapse.90.cc23.jpg'
 'https://assets.weather-forecast.com/maps/static/t_Yukon-Territory.lapse.90.cc23.jpg'
 'https://assets2.ello.co/images/fallback/user/cover_image/7/ello-default-optimized.jpg'
 'https://beermaps.com/wp-content/uploads/2019/03/BeerMaps-With-372x240.jpg'
 'https://boligpartnercdn-projects.imgix.net/Alle/0542/leira_i_valdres/71715fbc-d0b6-4b73-8d79-cd144bf2a05c/Kartutsnitt-Sore-Mano.jpg'
 'https://cbf-prod.s3.eu-central-1.amazonaws.com/countries/mm.png'
 'https://cdn-www.bnamericas.com/img/flags/ALL.jpg'
 'https://cdn.dhakapost.com/media/common/placeholder.jpg'
 'https://cdn.images.express.co.uk/img/dynamic/151/590x/secondary/eclipse-2018-when-is-super-blue-blood-moon-map-time-1214565.jpg'
 'https://cdn.working-dog.net/static/images/placeholder/no_dog_58_43.png'
 'https://cdn.working-dog.net/static/images/placeholder/no_dog_65_47.png'
 'https://cdn1.bodas.com.mx/assets/img/maps/placeholder_for_static_map.jpg'
 'https://cdn1.matrimonios.cl/assets/img/maps/placeholder_for_static_map.jpg'
 'https://cdn1.weddingwire.com/assets/img/maps/placeholder_for_static_map.jpg'
 'https://cdn10.agoda.net/images/MIN-9427/default/img-map-mosaic_v1.png'
 'https://community.adobe.com/t5/image/serverpage/avatar-name/mexican/avatar-theme/candy/avatar-collection/food/avatar-display-size/profile/version/2?xdesc=1.0'
 'https://concretefloorpros.com/wp-content/uploads/2019/01/Map_of_USA.jpg'
 'https://ediny-bilet.ru/wp-content/uploads/2019/05/img-2020-02-22-13-13-31.png'
 'https://fastly.4sqi.net/img/general/699x268/359176_imHiaSUjN-uax-a3rmo6jOyoVqpfK4D10sm6OjfFREA.jpg'
 'https://fr.car-2rent.com/en/images/car-hire-map.png'
 'https://gidra.de/oc-content/uploads/86/8131_thumbnail.jpg'
 'https://globalmobilemedia.com/template/images/default.jpg'
 'https://hide.me/resources/298/images/img_server_map.png'
 'https://hms.harvard.edu/sites/default/files/media/850RemoteAdmissions.jpg'
 'https://homemods.org/wp-content/uploads/2020/03/usmap.gold_-2048x1342.jpeg'
 'https://html.pdfcookie.com/02/2019/11/13/9lgr7j5kwr2o/bg5.jpg'
 'https://i.sms.at/profil/global/no_pic_location.jpg'
 'https://i0.wp.com/www.autogenius.info/wp-content/uploads/2016/09/Cadillac-CTS-mk1-fuse-box-engine-compartment-2005.jpg?w=1000'
 'https://images.spotzi.com/Website/business-cases/consumer-spending/3.jpg'
 'https://ippokratis.info/media/com_jbusinessdirectory/pictures/no_image.jpg'
 'https://lucidrealty.com/images/Chicago_Neighborhoods.jpg'
 'https://mappno.com/images/staticmap.jpg'
 'https://mymadrid.byethost7.com/imgpos/310x174Sz6qWtk_GfcsaI3QocOe_GrHFxdd3fSyvCPeKwj2C3nGw88PX85DG7tdh3oVgt4wZkw9c.webp'
 'https://mymadrid.byethost7.com/imgpos/310x174SzxIvRq-VB8kabBtRapdaGJmyxpibUgncuD2BkVGipXINZG2qu4S-OCHI2He-9eTqKH1I.webp'
 'https://mymadrid.byethost7.com/imgpos/310x496Szl93PmC323tXYNKin577dKagk1utbvDnHC5XGE44ol47sGZlH-zHQAskN7lrMaLPPEPs.webp'
 'https://peakoil.com/wp-content/themes/thebeeb/images/default.jpg'
 'https://perchn.com/themes/html5up-miniport/images/mapthumb2.jpg'
 'https://picsum.photos/800/620'
 'https://regio.outdooractive.com/api/staticmap?i=32972020&amp;size=large&amp;project=oar-hungary'
 'https://render.fineartamerica.com/images/rendered/search/print/images/artworkimages/medium/1/antique-map-of-naples-italian-school-.jpg'
 'https://s-media-cache-ak0.pinimg.com/216x146/58/11/ab/5811ab3bfb4fd129d429c298d9b3853c.jpg'
 'https://s.yimg.jp/images/ks/m/img/tlimg/2078297830_02.png'
 'https://s1.nordcdn.com/nordvpn/media/1.1061.0/images/download-hub/macos/hero-laptop-app.png'
 'https://static.flight-report.com/media/avatars/176/100_KTECFCCD_176.jpg'
 'https://static.samconveyancing.co.uk/userfiles/images/google-map.png'
 'https://thumbs01.cdn.web.tv/kh/gy/khgylwszmlo_1_300x165.jpg'
 'https://traductorjuradoportugues.es/wp-content/uploads/2021/06/portugues.png'
 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Guyanas.svg/1200px-Guyanas.svg.png'
 'https://www.austintexas.gov/sites/default/files/files/Water/PIO/boil_water_service_area_map.png'
 'https://www.beenverified.com/people/assets/dist/img/loading-map.jpg'
 'https://www.diamundialdelaarepa.com/wp-content/themes/supreme-directory/images/featured.jpg'
 'https://www.ehotelsreviews.com/static/img/maps-alternatives.jpg'
 'https://www.elkhadra.com/wp-content/uploads/2018/03/tn.png'
 'https://www.excellentlinks.nl/wp-content/uploads/2019/05/bedrijven-websites-online.png'
 'https://www.famous-germany.de/wp-content/uploads/flags/china-flagge.png'
 'https://www.gotembawalker.com/img/mypage-image/mypagenav-googlemap.png'
 'https://www.loc.gov/static/images/original-format/map.png?47615.43036'
 'https://www.loc.gov/static/images/original-format/map.png?55835.55929'
 'https://www.loveawake.com/view/templates/new/images/worldmap.png'
 'https://www.mscbsc.com/images/unit/yun_2.jpg'
 'https://www.originalmedia.eu/wordpress/wp-content/uploads/2018/03/loc8it-original-media-13-1920x1280.jpg'
 'https://www.promonix.com/uploads/img/flags-left/%E5%8F%B0%E7%81%A3.png'
 'https://www.telefoonboek.nl/images/steden/amsterdam.png'
 'https://www.telefoonboek.nl/images/steden/bathmen.png'
 'https://www.telefoonboek.nl/images/steden/haarlem.png'
 'https://www.telefoonboek.nl/images/steden/heiloo.png'
 'https://www.unrealbritain.com/media/com_jbusinessdirectory/pictures/no_image.jpg'
 'https://www.webmountindia.com/assets/images/city.jpg'
 'https://yellowpage.fixy.com.tw/pub/img/maps/location/map_tag1.png'
 'https://yellowpage.fixy.com.tw/pub/img/maps/location/map_tag10.png'
 'https://yellowpage.fixy.com.tw/pub/img/maps/location/map_tag15.png']

In [16]:
# sprawdz ile z nich jest już w finished
already_finished = np.isin(unique_urls, unique_urls_finished)
print(f"Already finished URLs: {already_finished.sum()}")

Already finished URLs: 164

In [4]:
import json

# Sprawdź strukturę
with open("all.json", "r") as f:
    data = json.load(f)

print(type(data))
print(f"Keys: {data.keys() if isinstance(data, dict) else 'Not a dict'}")

# Jeśli to dict - sprawdź długości
if isinstance(data, dict):
    for key, value in data.items():
        if isinstance(value, list):
            print(f"{key}: {len(value)} items")

<class 'dict'>
Keys: dict_keys(['part_0', 'part_1', 'part_2', 'part_3', 'part_4', 'part_5', 'part_6', 'part_7'])
part_0: 2985 items
part_1: 2985 items
part_2: 2985 items
part_3: 2984 items
part_4: 2984 items
part_5: 2983 items
part_6: 2984 items
part_7: 2984 items

In [7]:
df = pd.read_parquet('000229558fb8787ec73b7658d3874f4a.parquet')
3251*2984*8

77607872

In [9]:
df = pd.read_parquet('0020f0cbd157d470aa56bea08e304b90.parquet')
df.shape

(3100, 9)

In [10]:
df = pd.read_parquet('./data_preselection/checkpoint_137_rows_68500000.parquet')
# sort by score
df.tail()

,idx,url,score,pos_keys,neg_keys
499995,68499995,https://tantan-don.c.blog.so-net.ne.jp/_images...,0.0,,
499996,68499996,https://www.mostlymaps.com/upload/images/shopp...,0.0,,
499997,68499997,https://images.wikidexcdn.net/mwuploads/wikide...,0.0,,
499998,68499998,http://t0.gstatic.com/images?q=tbn:ANd9GcQJJRJ...,-3.0,,photos
499999,68499999,https://images.adsttc.com/media/image_maps/5b8...,0.0,,

In [ ]:
# 1. Wybrać losowo 200k próbek - samoling do ustalenia gdy zobaczymy finalny rozkład score słownika

def stratified_sample(df, n_samples):
    pass

# przesortować po indeksie

In [ ]:
# 2. Pobrać embeddingi dla tych 200k próbek (streaming)
df = pd.read_parquet('mappool_74M_scores_full.parquet')

# Stratyfikuj 200k indexów (bez sprawdzania URLs)
selected_indices = stratified_sample(df, 200_000)

# Pobierz embeddingi dla tych 200k
dataset = load_dataset("sraimund/MapPool", split="train", streaming=True)

embeddings = []
indices = []

for count, row in enumerate(tqdm(dataset, total=75_905_000, desc="Pobieranie embeddingów", unit=" rekordów")):
    if count in selected_indices:
        if 'embedding' in row and row['embedding'] is not None:
            embeddings.append(row['embedding'])
            indices.append(count)

        if len(indices) == len(selected_indices):
            break

np.savez_compressed('AL_embeddings_200k.npz',
                    embeddings=embeddings,
                    indices=indices)

In [ ]:
# 3.Merge metadata + embeddings
# 4. Przygotować interface do adnotacji ręcznej - prosty, pokazujemy mapę, score słownika, przyciski TAK/NIE/INVALID URL - gdy klikne INVALID URL to próbka automatycznie wyłączona z modelu i treningu - od razu przy budowaniu interfaceu i wyświetlaniu kolejnych obrazków dodac też automatyczne odrzucanie jesli status != 200 (ale przycisk musi byc jakbysmy wszystkiego nie wyłapali. Musi to pokazywać kolejne próbki do adnotacji, aż uzyska 3k próbek TAK/NIE. Zapisuje postępy/pozwala wznowić adnotację od ostatniego punktu.

# WYMAGANIA:
# ✅ Lazy loading obrazów (próba pobrania → auto-skip jeśli fail)
# ✅ HEAD request przed wyświetleniem (szybkie sprawdzenie)
# ✅ Przyciski: TAK / NIE / INVALID URL
# ✅ Keyboard shortcuts (Y/N/I)
# ✅ Pokazuj score słownika (jako hint)
# ✅ Progress tracking - zapisuj po każdej adnotacji
# ✅ Resume capability - wznów od ostatniego punktu
# ✅ Target: 3000 valid annotations (TAK lub NIE, bez INVALID)

# 5. Wybrać pulę stratyfikowaną do seed  (~10-15k żeby zdobyć 3k valid) - ok. 4h
# 6. Baseline model
# 7. Active Learning loop AL - sprawdzamy metryki, pobieramy niepewne do kolejnej stratyfikacji (600 próbek?)
# 8. Finalna ewaluacja - metryki
# 9. Finalna klasyfikacja 50M

# A. Streamuj dataset ponownie
# B. Dla każdego kandydata:
#    - Pobierz embedding
#    - Klasyfikuj modelem
#    - Jeśli positive → zapisz
# C. Dla pozytywnych - sprawdź URL (HEAD request)
# D. Finalny dataset: tylko pozytywne + działające URLs